### ISSUE TITLE
Calcular a distancia para a sequencia de clientes

### ISSUE THREAD

**Issue by gleydson404** [gleydson404/GA-CVRP#1]
Está calculando a distancia de um cliente para o outro, mas tem que verificar a questão da distancia do deposito ao primeiro cliente, e do ultimo cliente ao deposito. @Donegas Verifica isso.

**Comment by Donegas** [comment]
Função dist_veículo criada
Calcula as distâncias entre os clientes mais a saída e o retorno para o depósito baseado na matriz de distâncias. Retorna um vetor com a somatória por veículo.

**Comment by gleydson404** [comment]
Obrigado :+1: @Donegas
