### ISSUE TITLE
Rever questão da posição do deposito

### ISSUE THREAD

**Issue by gleydson404** [gleydson404/GA-CVRP#2]
A posição do deposito no arquivo é 1, mas os vetores começam de 0, temos que ver se não está ocorrendo erros de calculo devido ao index nas funções. 

Lá no arquivo, tem uma seção de depot, e que nos arquivos que eu olhei está 1, mas não sei se é pra todos os arquivos. 

@Donegas e @AlexRogaleski

**Comment by Donegas** [comment]
.
Até onde entendi sim, 1.
Acho que devíamos gerar os indivíduos sem o cliente 1 e pronto. Não resolveria nosso problema?
Eu fiz as funções de fitness desconsiderando o depósito no indivíduo, a distância até o depósito é a posição 0 da matriz de distâncias para toda a rota, tanto na saída (inicio da rota) quanto na chegada (fim da rota). 
Se vc calculou as coordenadas considerando o cliente 1 do arquivo como sendo os valores [0] da matriz, acho que não teremos problemas. Só lembrar de tirar o 1 na geração do indivíduo.

Confere?

**Comment by Donegas** [comment]
.
Agora que vi que a leitura do arquivo (customers) tem um "cliente" 0. A posição 0 deveria ser o cliente 1 e a geração de indivíduo não deve usá-lo. @AlexRogaleski, de onde vem o cliente 0 com as posições 0,0?

**Comment by Donegas** [comment]
.
Fiz um teste e está gerando sem o cliente 0. Podemos deixar assim ou mudar as funções de distancia e fitness. O que acham melhor?

**Comment by Donegas** [comment]
.
Mentira, mais difícil que eu pensei... Acho que não sei mexer com dicionários.
Vamos precisar discutir uma melhor maneira.

**Comment by AlexRogaleski** [comment]
É o que eu tava falando com o gleydson aquele dia a noite, o cliente [0: 0, 0 ,0] eu só inseri por que as outras funções utilizavam ele, ele nao esta no arquivo eu inseri pra corrigir o erro apenas.

**Comment by Donegas** [comment]
.
A Matriz é gerada com uma linha e coluna de 0s na posição (0, *) e ( *, 0).
As funções que utilizam a matriz: Dist_veiculo, Best_Insertion e Bounding Box estão calculando corretamente.
A distância entre clientes é a posição real dos clientes na matriz: De 3 a 18 é Dist_Matrix [3][18].

Pelos testes que fiz, acredito que este problema tenha sido resolvido.
