### ISSUE TITLE
Mutação simples com algum problema de indice

### ISSUE THREAD

**Issue by gleydson404** [gleydson404/GA-CVRP#4]
Da um crash de indice quando eu tento usar, to cadastrando rpa eu não esquecer, e não resolvi por que não deu tempo. @Donegas

**Comment by Donegas** [comment]
não consegui reproduzir o erro na mutação, mas no best_insertion, que ela chama, pq usa a dist_matrix e devia estar fora do range mesmo.
Testei e funcionou.
