### ISSUE TITLE
Uniform crossover gerando soluções infactiveis (com mais carros do que deveria no caso)

### ISSUE THREAD

**Issue by gleydson404** [gleydson404/GA-CVRP#6]

**Comment by Donegas** [comment]
.
Solução sugerida:
Usar a função Best_Insertion para saber em qual posição (rota, cliente) os clientes que sobraram devem entrar ao invés de formar uma nova rota com eles.

**Comment by gleydson404** [comment]
Corrigido, com best insertion e outras melhorias.
